---
title: "Contact & Payments"
editor: visual
---

# Payment Instructions

After we receive your payment via **Zelle, Cash App, or PayPal**, your consultation if needed will be scheduled and will take place within **48 hours**.

**A minimum payment of \$500** is required.

We strive to provide timely and professional guidance for all clients.

⚠️ Please securely submit all relevant datasets and files using the **"Secure Data Upload"** link provided on this page before your consultation**.**

## Zelle

Send payment to: bitadams\@udel.edu

## Cash App

Send payment to: **\$AdamBitunguramye**

## PayPal (International)

Send payment using PayPal:

<a href="https://paypal.me/Bitunguramye" class="button" target="_blank">Pay with PayPal</a>

------------------------------------------------------------------------

# Secure Data Upload

<a href="https://www.dropbox.com/request/ElRj2nROsRr6EwngrsC4" class="button">Upload Your File Securely</a>

------------------------------------------------------------------------

⚠️ **Please do NOT email sensitive health data containing patients' names.** Always share de-identified data. Maintaining confidentiality is essential.

**Note:** If you do not require a consultation or are short on time, you may upload one to two pages of instructions describing what you would like completed. Should we need any clarification, we will reach out to you.

## Contacts

**Email:**\
<a href="mailto:bitadams@udel.edu" class="button">Email Me</a>

**LinkedIn:**\
<a href="https://www.linkedin.com/in/adam-bitunguramye-464916257/" class="button" target="_blank">Visit My LinkedIn</a>
